apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: REPLACE_APP_NAME-REPLACE_ENV
  patch: |-
    - op: replace
      path: /metadata/name
      value: REPLACE_APP_NAME-REPLACE_ENV
    - op: replace
      path: /spec/source/path
      value: apps/REPLACE_APP_NAME/overlays/REPLACE_ENV
    - op: replace
      path: /spec/destination/namespace
      value: REPLACE_ENV
